mainModule:
  registerUrl: http://localhost:8080/registerer
  contentUrl: http://localhost:8080/content
  queueUrl: http://localhost:8080/queue

currentModule:
  moduleUrl: http://localhost:8081/
  mainUrl: https://www.wikipedia.org/
  sourceName: wikipedia.org

server:
  port: 8081

logging:
  file: app.log
  level:
    root: OFF
    com.musala.content: DEBUG

